#!/bin/sh
set -eu

export NOVELVOICE_DEVICE="${NOVELVOICE_DEVICE:-${SHUYI_DEVICE:-cpu}}"
export NOVELVOICE_MODEL_DIR="${NOVELVOICE_MODEL_DIR:-${SHUYI_MODEL_DIR:-/models}}"
export NOVELVOICE_DATA_DIR="${NOVELVOICE_DATA_DIR:-${SHUYI_DATA_DIR:-/data}}"
export NOVELVOICE_MODEL_AUTO_DOWNLOAD="${NOVELVOICE_MODEL_AUTO_DOWNLOAD:-${SHUYI_MODEL_AUTO_DOWNLOAD:-1}}"
export QWEN3_TTS_DEVICE="${QWEN3_TTS_DEVICE:-$NOVELVOICE_DEVICE}"
export QWEN3_TTS_MODEL_PATH="${QWEN3_TTS_MODEL_PATH:-$NOVELVOICE_MODEL_DIR/Qwen3-TTS-12Hz-1.7B-Base}"
export QWEN3_TTS_VOICE_DESIGN_MODEL_PATH="${QWEN3_TTS_VOICE_DESIGN_MODEL_PATH:-$NOVELVOICE_MODEL_DIR/Qwen3-TTS-12Hz-1.7B-VoiceDesign}"

mkdir -p "$NOVELVOICE_DATA_DIR" "$NOVELVOICE_MODEL_DIR"
python /app/scripts/container/download_models.py
exec python /app/scripts/container/supervise.py "$@"
